import {
  Tv,
  Car,
  GraduationCap,
  Utensils,
  Laptop,
  Gift,
  HeartPulse,
  Home,
  TrendingUp,
  Circle,
  Smile,
  Briefcase,
  ShoppingBag,
  Repeat,
  Plane,
  Zap,
  Building,
} from 'lucide-react'

export const ICONS: Record<string, any> = {
  building: Building,
  tv: Tv,
  car: Car,
  'graduation-cap': GraduationCap,
  utensils: Utensils,
  laptop: Laptop,
  gift: Gift,
  'heart-pulse': HeartPulse,
  home: Home,
  'trending-up': TrendingUp,
  circle: Circle,
  smile: Smile,
  briefcase: Briefcase,
  'shopping-bag': ShoppingBag,
  repeat: Repeat,
  plane: Plane,
  zap: Zap,
}